version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: pip install -U pip coveralls
      - run: pip install -U -r dev_requirements.txt
      - run:
          command: |
            coverage run --source=nickelodeon manage.py test --settings=nickelodeon.site.test_settings
          name: Test
      - run:
          command: coveralls
          name: Coveralls


workflows:
  main:
    jobs:
      - build-and-test