version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2022.04.2
      docker_layer_caching: false
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y libpq-dev
      - run: pip3 install -U -r requirements.txt
      - run: pip3 install coveralls
      - run: mkdir -p media/humppa-music
      - run: docker run -d -v media:/data -p 9000:9000 minio/minio:edge server /data
      - run:
          command: |
            coverage run --source=nickelodeon manage.py test --settings=nickelodeon.site.test_settings
          name: Test
          environment:
            PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      - run:
          command: python3 -m coveralls
          name: Upload coverage

workflows:
  main:
    jobs:
      - build-and-test
