# Generated by Django 2.2.11 on 2020-04-07 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nickelodeon", "0003_mp3song_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mp3song",
            name="filename",
            field=models.CharField(max_length=255, verbose_name="file name"),
        ),
        migrations.AlterUniqueTogether(
            name="mp3song",
            unique_together={("owner", "filename")},
        ),
    ]
