# Generated by Django 3.2.11 on 2022-01-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nickelodeon", "0007_alter_usersettings_storage_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
